---
# Install system-wide libraries

- name: Install python libs
  pip: name={{ item }}
  with_items:
    - supervisor
    - virtualenv
- name: Install python libs (pinned versions)
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - name: boto
      version: 2.34.0

